{
  pkgs,
  config,
  host,
  username,
  options,
  lib,
  inputs,
  system,
  ...
}: {
  imports = [
    ./bootloader.nix
    ./grub.nix
    ./plymouth.nix
    ./kernel.nix
    ./nh.nix
    ./audio.nix
    ./fonts.nix
    ./locale.nix
    ./system-hardware.nix
    ./stylix.nix
    ./system.nix
    ./services.nix
    ./security.nix
    ./flatpak.nix
    ./displaymanager.nix
    ./wayland.nix
    ./xfce.nix
    ./network.nix
    ./scheduler.nix
    ./virtualization.nix
    ./powermanagement.nix
    ./amd-drivers.nix
    ./nvidia-drivers.nix
    ./vm-guest-services.nix
    ./local-hardware-clock.nix
    ./cachix.nix
    ./packages.nix
    ./nix.nix
    ./niri.nix
    ./btrfs.nix
    ./zram.nix
  ];
}
