{
  config,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    ./home.nix
    ./git.nix
    ./gtk.nix
    ./cava.nix
    ./cliphist.nix
    ./nixy.nix
    ./fhsenv.nix
    ./hyprland.nix
    ./spicetify.nix
    ./home-packages.nix
    ./ghostty.nix
    ./equibop.nix
    ./variables.nix
    ./zathura.nix
    ./hypridle.nix
    ./anyrun
    ./niri/default.nix
    ./zellij/default.nix
    ./scripts/scripts.nix
    ./qt.nix
  ];
}
